# Generated by Django 5.1.2 on 2024-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=models.ImageField(upload_to='author_image/'),
        ),
    ]
