# Generated by Django 5.1.2 on 2024-11-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_post_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_job',
            field=models.CharField(default=313, max_length=221),
            preserve_default=False,
        ),
    ]
